title: Events in Context Knowledge Base 
description: Event data and where to find it and how to use it
theme: just-the-docs

url: https://events2025.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
