title: Events in Context
description: Event data and where to find it and how to use it
theme: just-the-docs

url: https://events2025.github.io

logo: "/assets/images/eventsInContext.png"

favicon_ico: "/assets/images/icon.ico"
