name: Run process_files.py on Push

on:
  push:
    branches:
      - main
      - develop  

jobs:
  run-process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run process_files.py
        run: |
          #rm Gemfile
          #rm Gemfile.lock
          cp data/Gemfile Gemfile
          cp data/Gemfile.lock Gemfile.lock
          touch Gemfile
          touch Gemfile.lock
          python main_create_website.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add .

            git commit -m "Automated update from process_files.py [skip ci]"

            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
